/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const COUNTRIES = [
  "United States", "Canada", "United Kingdom", "Australia", "India", "Germany", "France", "Japan", "China", "Brazil",
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Austria",
  "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
  "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde",
  "Cambodia", "Cameroon", "Central African Republic", "Chad", "Chile", "Colombia", "Comoros", "Congo", "Costa Rica",
  "Croatia", "Cuba", "Cyprus", "Czechia", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
  "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "Gabon",
  "Gambia", "Georgia", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guyana", "Haiti", "Honduras", "Hungary",
  "Iceland", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Jordan", "Kazakhstan", "Kenya",
  "Kiribati", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
  "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Mauritania",
  "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique",
  "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea",
  "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru",
  "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia",
  "Samoa", "San Marino", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia",
  "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka",
  "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste",
  "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine",
  "United Arab Emirates", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen",
  "Zambia", "Zimbabwe"
];

export const COUNTRY_DATA: Record<string, { flag: string; code: string }> = {
  "United States": { flag: "🇺🇸", code: "+1" },
  "Canada": { flag: "🇨🇦", code: "+1" },
  "United Kingdom": { flag: "🇬🇧", code: "+44" },
  "Australia": { flag: "🇦🇺", code: "+61" },
  "India": { flag: "🇮🇳", code: "+91" },
  "Germany": { flag: "🇩🇪", code: "+49" },
  "France": { flag: "🇫🇷", code: "+33" },
  "Japan": { flag: "🇯🇵", code: "+81" },
  "China": { flag: "🇨🇳", code: "+86" },
  "Brazil": { flag: "🇧🇷", code: "+55" },
  "Afghanistan": { flag: "🇦🇫", code: "+93" },
  "Albania": { flag: "🇦🇱", code: "+355" },
  "Algeria": { flag: "🇩🇿", code: "+213" },
  "Andorra": { flag: "🇦🇩", code: "+376" },
  "Angola": { flag: "🇦🇴", code: "+244" },
  "Antigua and Barbuda": { flag: "🇦🇬", code: "+1-268" },
  "Argentina": { flag: "🇦🇷", code: "+54" },
  "Armenia": { flag: "🇦🇲", code: "+374" },
  "Austria": { flag: "🇦🇹", code: "+43" },
  "Azerbaijan": { flag: "🇦🇿", code: "+994" },
  "Bahamas": { flag: "🇧🇸", code: "+1-242" },
  "Bahrain": { flag: "🇧🇭", code: "+973" },
  "Bangladesh": { flag: "🇧🇩", code: "+880" },
  "Barbados": { flag: "🇧🇧", code: "+1-246" },
  "Belarus": { flag: "🇧🇾", code: "+375" },
  "Belgium": { flag: "🇧🇪", code: "+32" },
  "Belize": { flag: "🇧🇿", code: "+501" },
  "Benin": { flag: "🇧🇯", code: "+229" },
  "Bhutan": { flag: "🇧🇹", code: "+975" },
  "Bolivia": { flag: "🇧🇴", code: "+591" },
  "Bosnia and Herzegovina": { flag: "🇧🇦", code: "+387" },
  "Botswana": { flag: "🇧🇼", code: "+267" },
  "Brunei": { flag: "🇧🇳", code: "+673" },
  "Bulgaria": { flag: "🇧🇬", code: "+359" },
  "Burkina Faso": { flag: "🇧🇫", code: "+226" },
  "Burundi": { flag: "🇧🇮", code: "+257" },
  "Cabo Verde": { flag: "🇨🇻", code: "+238" },
  "Cambodia": { flag: "🇰🇭", code: "+855" },
  "Cameroon": { flag: "🇨🇲", code: "+237" },
  "Central African Republic": { flag: "🇨🇫", code: "+236" },
  "Chad": { flag: "🇹🇩", code: "+235" },
  "Chile": { flag: "🇨🇱", code: "+56" },
  "Colombia": { flag: "🇨🇴", code: "+57" },
  "Comoros": { flag: "🇰🇲", code: "+269" },
  "Congo": { flag: "🇨🇬", code: "+242" },
  "Costa Rica": { flag: "🇨🇷", code: "+506" },
  "Croatia": { flag: "🇭🇷", code: "+385" },
  "Cuba": { flag: "🇨🇺", code: "+53" },
  "Cyprus": { flag: "🇨🇾", code: "+357" },
  "Czechia": { flag: "🇨🇿", code: "+420" },
  "Denmark": { flag: "🇩🇰", code: "+45" },
  "Djibouti": { flag: "🇩🇯", code: "+253" },
  "Dominica": { flag: "🇩🇲", code: "+1-767" },
  "Dominican Republic": { flag: "🇩🇴", code: "+1-809" },
  "Ecuador": { flag: "🇪🇨", code: "+593" },
  "Egypt": { flag: "🇪🇬", code: "+20" },
  "El Salvador": { flag: "🇸🇻", code: "+503" },
  "Equatorial Guinea": { flag: "🇬🇶", code: "+240" },
  "Eritrea": { flag: "🇪🇷", code: "+291" },
  "Estonia": { flag: "🇪🇪", code: "+372" },
  "Eswatini": { flag: "🇸🇿", code: "+268" },
  "Ethiopia": { flag: "🇪🇹", code: "+251" },
  "Fiji": { flag: "🇫🇯", code: "+679" },
  "Finland": { flag: "🇫🇮", code: "+358" },
  "Gabon": { flag: "🇬🇦", code: "+241" },
  "Gambia": { flag: "🇬🇲", code: "+220" },
  "Georgia": { flag: "🇬🇪", code: "+995" },
  "Ghana": { flag: "🇬🇭", code: "+233" },
  "Greece": { flag: "🇬🇷", code: "+30" },
  "Grenada": { flag: "🇬🇩", code: "+1-473" },
  "Guatemala": { flag: "🇬🇹", code: "+502" },
  "Guinea": { flag: "🇬🇳", code: "+224" },
  "Guyana": { flag: "🇬🇾", code: "+592" },
  "Haiti": { flag: "🇭🇹", code: "+509" },
  "Honduras": { flag: "🇭🇳", code: "+504" },
  "Hungary": { flag: "🇭🇺", code: "+36" },
  "Iceland": { flag: "🇮🇸", code: "+354" },
  "Indonesia": { flag: "🇮🇩", code: "+62" },
  "Iran": { flag: "🇮🇷", code: "+98" },
  "Iraq": { flag: "🇮🇶", code: "+964" },
  "Ireland": { flag: "🇮🇪", code: "+353" },
  "Israel": { flag: "🇮🇱", code: "+972" },
  "Italy": { flag: "🇮🇹", code: "+39" },
  "Jamaica": { flag: "🇯🇲", code: "+1-876" },
  "Jordan": { flag: "🇯🇴", code: "+962" },
  "Kazakhstan": { flag: "🇰🇿", code: "+7" },
  "Kenya": { flag: "🇰🇪", code: "+254" },
  "Kiribati": { flag: "🇰🇮", code: "+686" },
  "Kuwait": { flag: "🇰🇼", code: "+965" },
  "Kyrgyzstan": { flag: "🇰🇬", code: "+996" },
  "Laos": { flag: "🇱🇦", code: "+856" },
  "Latvia": { flag: "🇱🇻", code: "+371" },
  "Lebanon": { flag: "🇱🇧", code: "+961" },
  "Lesotho": { flag: "🇱🇸", code: "+266" },
  "Liberia": { flag: "🇱🇷", code: "+231" },
  "Libya": { flag: "🇱🇾", code: "+218" },
  "Liechtenstein": { flag: "🇱🇮", code: "+423" },
  "Lithuania": { flag: "🇱🇹", code: "+370" },
  "Luxembourg": { flag: "🇱🇺", code: "+352" },
  "Madagascar": { flag: "🇲🇬", code: "+261" },
  "Malawi": { flag: "🇲🇼", code: "+265" },
  "Malaysia": { flag: "🇲🇾", code: "+60" },
  "Maldives": { flag: "🇲🇻", code: "+960" },
  "Mali": { flag: "🇲🇱", code: "+223" },
  "Malta": { flag: "🇲🇹", code: "+356" },
  "Mauritania": { flag: "🇲🇷", code: "+222" },
  "Mauritius": { flag: "🇲🇺", code: "+230" },
  "Mexico": { flag: "🇲🇽", code: "+52" },
  "Micronesia": { flag: "🇫🇲", code: "+691" },
  "Moldova": { flag: "🇲🇩", code: "+373" },
  "Monaco": { flag: "🇲🇨", code: "+377" },
  "Mongolia": { flag: "🇲🇳", code: "+976" },
  "Montenegro": { flag: "🇲🇪", code: "+382" },
  "Morocco": { flag: "🇲🇦", code: "+212" },
  "Mozambique": { flag: "🇲🇿", code: "+258" },
  "Myanmar": { flag: "🇲🇲", code: "+95" },
  "Namibia": { flag: "🇳🇦", code: "+264" },
  "Nauru": { flag: "🇳🇷", code: "+674" },
  "Nepal": { flag: "🇳🇵", code: "+977" },
  "Netherlands": { flag: "🇳🇱", code: "+31" },
  "New Zealand": { flag: "🇳🇿", code: "+64" },
  "Nicaragua": { flag: "🇳🇮", code: "+505" },
  "Niger": { flag: "🇳🇪", code: "+227" },
  "Nigeria": { flag: "🇳🇬", code: "+234" },
  "North Korea": { flag: "🇰🇵", code: "+850" },
  "North Macedonia": { flag: "🇲🇰", code: "+389" },
  "Norway": { flag: "🇳🇴", code: "+47" },
  "Oman": { flag: "🇴🇲", code: "+968" },
  "Pakistan": { flag: "🇵🇰", code: "+92" },
  "Palau": { flag: "🇵🇼", code: "+680" },
  "Panama": { flag: "🇵🇦", code: "+507" },
  "Papua New Guinea": { flag: "🇵🇬", code: "+675" },
  "Paraguay": { flag: "🇵🇾", code: "+595" },
  "Peru": { flag: "🇵🇪", code: "+51" },
  "Philippines": { flag: "🇵🇭", code: "+63" },
  "Poland": { flag: "🇵🇱", code: "+48" },
  "Portugal": { flag: "🇵🇹", code: "+351" },
  "Qatar": { flag: "🇶🇦", code: "+974" },
  "Romania": { flag: "🇷🇴", code: "+40" },
  "Russia": { flag: "🇷🇺", code: "+7" },
  "Rwanda": { flag: "🇷🇼", code: "+250" },
  "Saint Kitts and Nevis": { flag: "🇰🇳", code: "+1-869" },
  "Saint Lucia": { flag: "🇱🇨", code: "+1-758" },
  "Samoa": { flag: "🇼🇸", code: "+685" },
  "San Marino": { flag: "🇸🇲", code: "+378" },
  "Saudi Arabia": { flag: "🇸🇦", code: "+966" },
  "Senegal": { flag: "🇸🇳", code: "+221" },
  "Serbia": { flag: "🇷🇸", code: "+381" },
  "Seychelles": { flag: "🇸🇨", code: "+248" },
  "Sierra Leone": { flag: "🇸🇱", code: "+232" },
  "Singapore": { flag: "🇸🇬", code: "+65" },
  "Slovakia": { flag: "🇸🇰", code: "+421" },
  "Slovenia": { flag: "🇸🇮", code: "+386" },
  "Solomon Islands": { flag: "🇸🇧", code: "+677" },
  "Somalia": { flag: "🇸🇴", code: "+252" },
  "South Africa": { flag: "🇿🇦", code: "+27" },
  "South Korea": { flag: "🇰🇷", code: "+82" },
  "South Sudan": { flag: "🇸🇸", code: "+211" },
  "Spain": { flag: "🇪🇸", code: "+34" },
  "Sri Lanka": { flag: "🇱🇰", code: "+94" },
  "Sudan": { flag: "🇸🇩", code: "+249" },
  "Suriname": { flag: "🇸🇷", code: "+597" },
  "Sweden": { flag: "🇸🇪", code: "+46" },
  "Switzerland": { flag: "🇨🇭", code: "+41" },
  "Syria": { flag: "🇸🇾", code: "+963" },
  "Taiwan": { flag: "🇹🇼", code: "+886" },
  "Tajikistan": { flag: "🇹🇯", code: "+992" },
  "Tanzania": { flag: "🇹🇿", code: "+255" },
  "Thailand": { flag: "🇹🇭", code: "+66" },
  "Timor-Leste": { flag: "🇹🇱", code: "+670" },
  "Togo": { flag: "🇹🇬", code: "+228" },
  "Tonga": { flag: "🇹🇴", code: "+676" },
  "Trinidad and Tobago": { flag: "🇹🇹", code: "+1-868" },
  "Tunisia": { flag: "🇹🇳", code: "+216" },
  "Turkey": { flag: "🇹🇷", code: "+90" },
  "Turkmenistan": { flag: "🇹🇲", code: "+993" },
  "Tuvalu": { flag: "🇹🇻", code: "+688" },
  "Uganda": { flag: "🇺🇬", code: "+256" },
  "Ukraine": { flag: "🇺🇦", code: "+380" },
  "United Arab Emirates": { flag: "🇦🇪", code: "+971" },
  "Uruguay": { flag: "🇺🇾", code: "+598" },
  "Uzbekistan": { flag: "🇺🇿", code: "+998" },
  "Vanuatu": { flag: "🇻🇺", code: "+678" },
  "Vatican City": { flag: "🇻🇦", code: "+39-06" },
  "Venezuela": { flag: "🇻🇪", code: "+58" },
  "Vietnam": { flag: "🇻🇳", code: "+84" },
  "Yemen": { flag: "🇾🇪", code: "+967" },
  "Zambia": { flag: "🇿🇲", code: "+260" },
  "Zimbabwe": { flag: "🇿🇼", code: "+263" }
};
