/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { eq, desc } from 'drizzle-orm';
import { db } from '../../src/db/index.ts';
import { teamCommissionHistory, users } from '../../src/db/schema.ts';

export class TeamCommissionHistoryRepository {
  /**
   * Record one Team Commission payout. Called ONLY by ReferralService — the
   * single owning Service for all Team Commission logic (Section 17).
   */
  async createRecord(data: {
    receiverUserId: string;
    sourceUserId: string;
    claimId: string;
    level: number;
    sourceDpyAmount: string;
    commissionAmount: string;
  }) {
    try {
      const result = await db
        .insert(teamCommissionHistory)
        .values({
          receiverUserId: data.receiverUserId,
          sourceUserId: data.sourceUserId,
          claimId: data.claimId,
          level: data.level,
          sourceDpyAmount: data.sourceDpyAmount,
          commissionAmount: data.commissionAmount,
        })
        .returning();
      return result[0];
    } catch (error) {
      console.error('Database insertion (createRecord) failed:', error);
      throw new Error('Failed to record team commission history.');
    }
  }

  /**
   * Retrieve a receiving user's Team Commission history, paginated, newest first.
   * Joins the Users table to resolve the source user's username at query time —
   * username is never stored on this table (Users table is the single source of
   * truth for identity).
   *
   * Required by the Controller Layer to render the History UI table:
   * Time | Username | Level | DPY Claimed | Commission Earned.
   */
  async getHistoryByReceiverId(receiverUserId: string, options?: { limit?: number; offset?: number }) {
    try {
      const limit = options?.limit ?? 50;
      const offset = options?.offset ?? 0;

      const result = await db
        .select({
          id: teamCommissionHistory.id,
          createdAt: teamCommissionHistory.createdAt,
          sourceUserId: teamCommissionHistory.sourceUserId,
          sourceUsername: users.username,
          level: teamCommissionHistory.level,
          sourceDpyAmount: teamCommissionHistory.sourceDpyAmount,
          commissionAmount: teamCommissionHistory.commissionAmount,
        })
        .from(teamCommissionHistory)
        .innerJoin(users, eq(teamCommissionHistory.sourceUserId, users.id))
        .where(eq(teamCommissionHistory.receiverUserId, receiverUserId))
        .orderBy(desc(teamCommissionHistory.createdAt))
        .limit(limit)
        .offset(offset);

      return result;
    } catch (error) {
      console.error('Database query (getHistoryByReceiverId) failed:', error);
      throw new Error('Failed to load team commission history.');
    }
  }

  /**
   * Retrieve every commission record generated by a single DPY claim
   * (used for internal verification / admin audit lookups).
   */
  async getHistoryByClaimId(claimId: string) {
    try {
      const result = await db
        .select()
        .from(teamCommissionHistory)
        .where(eq(teamCommissionHistory.claimId, claimId));
      return result;
    } catch (error) {
      console.error('Database query (getHistoryByClaimId) failed:', error);
      throw new Error('Failed to load team commission records for claim.');
    }
  }
}

export const teamCommissionHistoryRepository = new TeamCommissionHistoryRepository();
export default teamCommissionHistoryRepository;
